"""add fields to survey 2

Revision ID: 101a0b831ecc
Revises: 75768f5591bc
Create Date: 2025-11-09 19:48:50.836178

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "101a0b831ecc"
down_revision: Union[str, Sequence[str], None] = "75768f5591bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "survey_2", sa.Column("visit_date", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "survey_2", sa.Column("attended_by", sa.String(length=255), nullable=True)
    )
    op.add_column("survey_2", sa.Column("user", sa.String(length=255), nullable=True))
    op.add_column(
        "survey_2", sa.Column("worker_up", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "survey_2", sa.Column("Household_size", sa.String(length=50), nullable=True)
    )
    op.add_column("survey_2", sa.Column("other", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("survey_2", "other")
    op.drop_column("survey_2", "Household_size")
    op.drop_column("survey_2", "worker_up")
    op.drop_column("survey_2", "user")
    op.drop_column("survey_2", "attended_by")
    op.drop_column("survey_2", "visit_date")
    # ### end Alembic commands ###
