"""update log admin

Revision ID: 1634fa447652
Revises: 7b4f9544151c
Create Date: 2025-11-14 16:22:34.331228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1634fa447652'
down_revision: Union[str, Sequence[str], None] = '7b4f9544151c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'admin_logger', 'user_admin', ['admin_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_logger', type_='foreignkey')
    # ### end Alembic commands ###
