"""Change ethnic_belonging to boolean in user_producter

Revision ID: 3646f39f31c1
Revises: 73f98cdaa143
Create Date: 2025-11-24 16:40:04.125373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3646f39f31c1'
down_revision: Union[str, Sequence[str], None] = '73f98cdaa143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    connection.execute(
        sa.text(
            """
            UPDATE user_producter
            SET ethnic_belonging = CASE
                WHEN ethnic_belonging IS NULL THEN NULL
                WHEN TRIM(LOWER(ethnic_belonging)) IN ('true', 't', '1') THEN 'true'
                WHEN TRIM(LOWER(ethnic_belonging)) IN ('false', 'f', '0') THEN 'false'
                ELSE NULL
            END
            """
        )
    )
    op.alter_column('user_producter', 'ethnic_belonging',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using='ethnic_belonging::boolean')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_producter', 'ethnic_belonging',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    # ### end Alembic commands ###
