"""Initial migration

Revision ID: 54789b96ffea
Revises: 
Create Date: 2025-10-15 18:46:51.808702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54789b96ffea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_property',
    sa.Column('user_producter_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.Column('asnm', sa.String(length=50), nullable=True),
    sa.Column('total_area', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_extensionist',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('identification', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('signing_image_path', sa.String(length=255), nullable=True),
    sa.Column('api_token', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_extensionist_api_token'), 'user_extensionist', ['api_token'], unique=True)
    op.create_table('user_producter',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('identification', sa.String(length=50), nullable=True),
    sa.Column('is_woman_rural', sa.Boolean(), nullable=True),
    sa.Column('is_young_rural', sa.Boolean(), nullable=True),
    sa.Column('ethnic_belonging', sa.String(length=150), nullable=True),
    sa.Column('is_victim_conflict', sa.Boolean(), nullable=True),
    sa.Column('is_narp', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_producter')
    op.drop_index(op.f('ix_user_extensionist_api_token'), table_name='user_extensionist')
    op.drop_table('user_extensionist')
    op.drop_table('product_property')
    # ### end Alembic commands ###
