"""add common fields to survey 1

Revision ID: 5a7510384b4c
Revises: b09ab1324207
Create Date: 2025-11-09 20:07:31.527918

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a7510384b4c"
down_revision: Union[str, Sequence[str], None] = "b09ab1324207"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "survey_1", sa.Column("visit_date", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "survey_1", sa.Column("attended_by", sa.String(length=255), nullable=True)
    )
    op.add_column("survey_1", sa.Column("user", sa.String(length=255), nullable=True))
    op.add_column(
        "survey_1", sa.Column("worker_up", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "survey_1", sa.Column("household_size", sa.String(length=50), nullable=True)
    )
    op.add_column("survey_1", sa.Column("other", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("survey_1", "other")
    op.drop_column("survey_1", "household_size")
    op.drop_column("survey_1", "worker_up")
    op.drop_column("survey_1", "user")
    op.drop_column("survey_1", "attended_by")
    op.drop_column("survey_1", "visit_date")
    # ### end Alembic commands ###
