"""removed field

Revision ID: 6b7819a6c22e
Revises: 1e5125fd5cb3
Create Date: 2025-11-21 15:48:17.825366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b7819a6c22e'
down_revision: Union[str, Sequence[str], None] = '1e5125fd5cb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_1', 'household_size')
    op.drop_column('survey_1', 'other')
    op.drop_column('survey_1', 'worker_up')
    op.drop_column('survey_1', 'user')
    op.drop_column('survey_2', 'household_size')
    op.drop_column('survey_2', 'other')
    op.drop_column('survey_2', 'worker_up')
    op.drop_column('survey_2', 'user')
    op.drop_column('survey_3', 'household_size')
    op.drop_column('survey_3', 'other')
    op.drop_column('survey_3', 'worker_up')
    op.drop_column('survey_3', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_3', sa.Column('user', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('survey_3', sa.Column('worker_up', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('survey_3', sa.Column('other', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('survey_3', sa.Column('household_size', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('survey_2', sa.Column('user', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('survey_2', sa.Column('worker_up', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('survey_2', sa.Column('other', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('survey_2', sa.Column('household_size', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('survey_1', sa.Column('user', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('survey_1', sa.Column('worker_up', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('survey_1', sa.Column('other', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('survey_1', sa.Column('household_size', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
