"""removed fields in surveys

Revision ID: 73f98cdaa143
Revises: 6b7819a6c22e
Create Date: 2025-11-22 15:14:28.715154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73f98cdaa143'
down_revision: Union[str, Sequence[str], None] = '6b7819a6c22e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_1', 'other_acompanamiento')
    op.drop_column('survey_1', 'type_acompanamiento')
    op.drop_column('survey_1', 'copy_documentation_delivered')
    op.drop_column('survey_2', 'other_acompanamiento')
    op.drop_column('survey_2', 'type_acompanamiento')
    op.drop_column('survey_2', 'copy_documentation_delivered')
    op.drop_column('survey_3', 'other_acompanamiento')
    op.drop_column('survey_3', 'type_acompanamiento')
    op.drop_column('survey_3', 'copy_documentation_delivered')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_3', sa.Column('copy_documentation_delivered', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('survey_3', sa.Column('type_acompanamiento', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('survey_3', sa.Column('other_acompanamiento', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('survey_2', sa.Column('copy_documentation_delivered', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('survey_2', sa.Column('type_acompanamiento', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('survey_2', sa.Column('other_acompanamiento', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('survey_1', sa.Column('copy_documentation_delivered', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('survey_1', sa.Column('type_acompanamiento', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('survey_1', sa.Column('other_acompanamiento', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
