"""update surveys models

Revision ID: 75768f5591bc
Revises: 973c3ffd885a
Create Date: 2025-11-04 09:55:11.258350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75768f5591bc'
down_revision: Union[str, Sequence[str], None] = '973c3ffd885a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_property', 'area_total_linea_productive_primary')
    op.drop_column('product_property', 'area_total_linea_productive_secondary')
    op.drop_column('product_property', 'total_area')
    op.add_column('survey_1', sa.Column('observations_visited', sa.String(length=500), nullable=True))
    op.add_column('survey_1', sa.Column('date_hour_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('survey_1', sa.Column('copy_documentation_delivered', sa.String(length=50), nullable=True))
    op.add_column('survey_1', sa.Column('date_acompanamiento', sa.String(length=50), nullable=True))
    op.add_column('survey_1', sa.Column('hour_acompanamiento', sa.String(length=50), nullable=True))
    op.add_column('survey_1', sa.Column('origen_register', sa.String(length=100), nullable=True))
    op.add_column('survey_1', sa.Column('name_acompanamiento', sa.String(length=100), nullable=True))
    op.add_column('survey_1', sa.Column('type_acompanamiento', sa.String(length=100), nullable=True))
    op.add_column('survey_1', sa.Column('other_acompanamiento', sa.String(length=100), nullable=True))
    op.drop_column('survey_1', 'observations')
    op.drop_column('survey_1', 'other')
    op.drop_column('survey_1', 'user')
    op.drop_column('survey_1', 'worker_up')
    op.drop_column('survey_1', 'visit_date')
    op.drop_column('survey_1', 'Household_size')
    op.drop_column('survey_1', 'attended_by')
    op.add_column('survey_2', sa.Column('observations_visited', sa.String(length=700), nullable=True))
    op.add_column('survey_2', sa.Column('date_acompanamiento', sa.String(length=50), nullable=True))
    op.add_column('survey_2', sa.Column('hour_acompanamiento', sa.String(length=50), nullable=True))
    op.add_column('survey_2', sa.Column('origen_register', sa.String(length=100), nullable=True))
    op.add_column('survey_2', sa.Column('name_acompanamiento', sa.String(length=100), nullable=True))
    op.add_column('survey_2', sa.Column('type_acompanamiento', sa.String(length=100), nullable=True))
    op.add_column('survey_2', sa.Column('other_acompanamiento', sa.String(length=100), nullable=True))
    op.drop_column('survey_2', 'observations')
    op.drop_column('survey_2', 'other')
    op.drop_column('survey_2', 'user')
    op.drop_column('survey_2', 'worker_up')
    op.drop_column('survey_2', 'visit_date')
    op.drop_column('survey_2', 'Household_size')
    op.drop_column('survey_2', 'attended_by')
    op.add_column('survey_3', sa.Column('development_accompaniment', sa.String(length=500), nullable=True))
    op.add_column('survey_3', sa.Column('final_diagnosis', sa.String(length=500), nullable=True))
    op.add_column('survey_3', sa.Column('observations_visited', sa.String(length=500), nullable=True))
    op.add_column('survey_3', sa.Column('date_acompanamiento', sa.String(length=50), nullable=True))
    op.add_column('survey_3', sa.Column('hour_acompanamiento', sa.String(length=50), nullable=True))
    op.add_column('survey_3', sa.Column('origen_register', sa.String(length=100), nullable=True))
    op.add_column('survey_3', sa.Column('name_acompanamiento', sa.String(length=100), nullable=True))
    op.add_column('survey_3', sa.Column('type_acompanamiento', sa.String(length=100), nullable=True))
    op.add_column('survey_3', sa.Column('other_acompanamiento', sa.String(length=100), nullable=True))
    op.add_column('survey_3', sa.Column('date_hour_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('survey_3', sa.Column('copy_documentation_delivered', sa.String(length=50), nullable=True))
    op.add_column('survey_3', sa.Column('socialization_events_group', sa.String(length=500), nullable=True))
    op.add_column('survey_3', sa.Column('not_agend_new_visit', sa.String(length=500), nullable=True))
    op.drop_column('survey_3', 'initial_diagnosis')
    op.drop_column('survey_3', 'observations')
    op.drop_column('survey_3', 'other')
    op.drop_column('survey_3', 'user')
    op.drop_column('survey_3', 'worker_up')
    op.drop_column('survey_3', 'visit_date')
    op.drop_column('survey_3', 'Household_size')
    op.drop_column('survey_3', 'attended_by')
    op.add_column('user_producter', sa.Column('number_phone', sa.String(length=50), nullable=True))
    op.add_column('user_producter', sa.Column('is_producer_organization_member', sa.Boolean(), nullable=True))
    op.add_column('user_producter', sa.Column('organization_name', sa.String(length=255), nullable=True))
    op.add_column('user_producter', sa.Column('representantive1_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_producter', 'representantive1_name')
    op.drop_column('user_producter', 'organization_name')
    op.drop_column('user_producter', 'is_producer_organization_member')
    op.drop_column('user_producter', 'number_phone')
    op.add_column('survey_3', sa.Column('attended_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('survey_3', sa.Column('Household_size', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('survey_3', sa.Column('visit_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('survey_3', sa.Column('worker_up', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('survey_3', sa.Column('user', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('survey_3', sa.Column('other', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('survey_3', sa.Column('observations', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('survey_3', sa.Column('initial_diagnosis', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('survey_3', 'not_agend_new_visit')
    op.drop_column('survey_3', 'socialization_events_group')
    op.drop_column('survey_3', 'copy_documentation_delivered')
    op.drop_column('survey_3', 'date_hour_end')
    op.drop_column('survey_3', 'other_acompanamiento')
    op.drop_column('survey_3', 'type_acompanamiento')
    op.drop_column('survey_3', 'name_acompanamiento')
    op.drop_column('survey_3', 'origen_register')
    op.drop_column('survey_3', 'hour_acompanamiento')
    op.drop_column('survey_3', 'date_acompanamiento')
    op.drop_column('survey_3', 'observations_visited')
    op.drop_column('survey_3', 'final_diagnosis')
    op.drop_column('survey_3', 'development_accompaniment')
    op.add_column('survey_2', sa.Column('attended_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('survey_2', sa.Column('Household_size', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('survey_2', sa.Column('visit_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('survey_2', sa.Column('worker_up', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('survey_2', sa.Column('user', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('survey_2', sa.Column('other', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('survey_2', sa.Column('observations', sa.VARCHAR(length=700), autoincrement=False, nullable=True))
    op.drop_column('survey_2', 'other_acompanamiento')
    op.drop_column('survey_2', 'type_acompanamiento')
    op.drop_column('survey_2', 'name_acompanamiento')
    op.drop_column('survey_2', 'origen_register')
    op.drop_column('survey_2', 'hour_acompanamiento')
    op.drop_column('survey_2', 'date_acompanamiento')
    op.drop_column('survey_2', 'observations_visited')
    op.add_column('survey_1', sa.Column('attended_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('survey_1', sa.Column('Household_size', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('survey_1', sa.Column('visit_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('survey_1', sa.Column('worker_up', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('survey_1', sa.Column('user', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('survey_1', sa.Column('other', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('survey_1', sa.Column('observations', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('survey_1', 'other_acompanamiento')
    op.drop_column('survey_1', 'type_acompanamiento')
    op.drop_column('survey_1', 'name_acompanamiento')
    op.drop_column('survey_1', 'origen_register')
    op.drop_column('survey_1', 'hour_acompanamiento')
    op.drop_column('survey_1', 'date_acompanamiento')
    op.drop_column('survey_1', 'copy_documentation_delivered')
    op.drop_column('survey_1', 'date_hour_end')
    op.drop_column('survey_1', 'observations_visited')
    op.add_column('product_property', sa.Column('total_area', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('product_property', sa.Column('area_total_linea_productive_secondary', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('product_property', sa.Column('area_total_linea_productive_primary', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
