"""Convert JSONB fields with data migration

Revision ID: 7b4f9544151c
Revises: 5a7510384b4c
Create Date: 2025-11-11 14:23:20.503908

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7b4f9544151c"
down_revision: Union[str, Sequence[str], None] = "5a7510384b4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "survey_1",
        "objetive_accompaniment",
        existing_type=sa.VARCHAR(length=500),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        postgresql_using="to_jsonb(objetive_accompaniment)",
    )
    op.add_column(
        "survey_2", sa.Column("household_size", sa.String(length=50), nullable=True)
    )
    op.alter_column(
        "survey_2",
        "objective_accompaniment",
        existing_type=sa.VARCHAR(length=500),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        postgresql_using="to_jsonb(objective_accompaniment)",
    )
    op.drop_column("survey_2", "Household_size")
    op.alter_column(
        "survey_3",
        "objetive_accompaniment",
        existing_type=sa.VARCHAR(length=500),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        postgresql_using="to_jsonb(objetive_accompaniment)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "survey_3",
        "objetive_accompaniment",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.VARCHAR(length=500),
        existing_nullable=True,
    )
    op.add_column(
        "survey_2",
        sa.Column(
            "Household_size", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.alter_column(
        "survey_2",
        "objective_accompaniment",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.VARCHAR(length=500),
        existing_nullable=True,
    )
    op.drop_column("survey_2", "household_size")
    op.alter_column(
        "survey_1",
        "objetive_accompaniment",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.VARCHAR(length=500),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
