"""Consolidate user models

Revision ID: 9a7412e3d753
Revises: 
Create Date: 2025-10-16 12:58:43.176282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a7412e3d753'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_property',
    sa.Column('user_producter_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.Column('asnm', sa.String(length=50), nullable=True),
    sa.Column('total_area', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_extensionist',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('identification', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('signing_image_path', sa.String(length=255), nullable=True),
    sa.Column('api_token', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_extensionist_api_token'), 'user_extensionist', ['api_token'], unique=True)
    op.create_table('user_producter',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('identification', sa.String(length=50), nullable=True),
    sa.Column('is_woman_rural', sa.Boolean(), nullable=True),
    sa.Column('is_young_rural', sa.Boolean(), nullable=True),
    sa.Column('ethnic_belonging', sa.String(length=150), nullable=True),
    sa.Column('is_victim_conflict', sa.Boolean(), nullable=True),
    sa.Column('is_narp', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_1',
    sa.Column('extensionist_id', sa.Integer(), nullable=True),
    sa.Column('producter_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('attended_by', sa.String(length=255), nullable=True),
    sa.Column('attended_role', sa.String(length=100), nullable=True),
    sa.Column('human_technical_capacities', sa.Text(), nullable=True),
    sa.Column('social_associativity', sa.Text(), nullable=True),
    sa.Column('technology_access', sa.Text(), nullable=True),
    sa.Column('natural_resources_management', sa.Text(), nullable=True),
    sa.Column('public_policy_participation', sa.Text(), nullable=True),
    sa.Column('is_woman_rural', sa.Boolean(), nullable=True),
    sa.Column('is_young_rural', sa.Boolean(), nullable=True),
    sa.Column('ethnic_belonging', sa.Boolean(), nullable=True),
    sa.Column('is_narp', sa.Boolean(), nullable=True),
    sa.Column('is_victim_conflict', sa.Boolean(), nullable=True),
    sa.Column('control_resources', sa.Integer(), nullable=True),
    sa.Column('control_resources_obs', sa.Text(), nullable=True),
    sa.Column('decision_voice', sa.Integer(), nullable=True),
    sa.Column('decision_voice_obs', sa.Text(), nullable=True),
    sa.Column('innovation_leadership', sa.Integer(), nullable=True),
    sa.Column('innovation_leadership_obs', sa.Text(), nullable=True),
    sa.Column('knowledge_dialogue', sa.Integer(), nullable=True),
    sa.Column('knowledge_dialogue_obs', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('initial_diagnosis', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('photo_user', sa.String(length=255), nullable=True),
    sa.Column('photo_interaction', sa.String(length=255), nullable=True),
    sa.Column('photo_panorama', sa.String(length=255), nullable=True),
    sa.Column('phono_extra_1', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['extensionist_id'], ['user_extensionist.id'], ),
    sa.ForeignKeyConstraint(['producter_id'], ['user_producter.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['product_property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_2',
    sa.Column('extensionist_id', sa.Integer(), nullable=True),
    sa.Column('producter_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('attended_by', sa.String(length=255), nullable=True),
    sa.Column('attended_role', sa.String(length=100), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('visit_followup', sa.Text(), nullable=True),
    sa.Column('fulfilled_previous_recommendations', sa.Boolean(), nullable=True),
    sa.Column('new_recommendations', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('co_innovation_identified', sa.Boolean(), nullable=True),
    sa.Column('co_innovation_consent', sa.Boolean(), nullable=True),
    sa.Column('innovation_name', sa.String(length=255), nullable=True),
    sa.Column('innovation_description', sa.Text(), nullable=True),
    sa.Column('innovation_problem_solved', sa.Text(), nullable=True),
    sa.Column('innovation_origin', sa.String(), nullable=True),
    sa.Column('innovation_materials', sa.Text(), nullable=True),
    sa.Column('innovation_process', sa.Text(), nullable=True),
    sa.Column('innovation_scalability', sa.Text(), nullable=True),
    sa.Column('innovation_observations', sa.Text(), nullable=True),
    sa.Column('photo_user', sa.String(length=255), nullable=True),
    sa.Column('photo_interaction', sa.String(length=255), nullable=True),
    sa.Column('photo_panorama', sa.String(length=255), nullable=True),
    sa.Column('photo_innovation_1', sa.String(length=255), nullable=True),
    sa.Column('photo_innovation_2', sa.String(length=255), nullable=True),
    sa.Column('photo_innovation_3', sa.String(length=255), nullable=True),
    sa.Column('photo_innovation_4', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['extensionist_id'], ['user_extensionist.id'], ),
    sa.ForeignKeyConstraint(['producter_id'], ['user_producter.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['product_property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_3',
    sa.Column('extensionist_id', sa.Integer(), nullable=True),
    sa.Column('producter_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('attended_by', sa.String(length=255), nullable=True),
    sa.Column('attended_role', sa.String(length=100), nullable=True),
    sa.Column('human_technical_capacities', sa.Text(), nullable=True),
    sa.Column('social_associativity', sa.Text(), nullable=True),
    sa.Column('technology_access', sa.Text(), nullable=True),
    sa.Column('natural_resources_management', sa.Text(), nullable=True),
    sa.Column('public_policy_participation', sa.Text(), nullable=True),
    sa.Column('is_woman_rural', sa.Boolean(), nullable=True),
    sa.Column('is_young_rural', sa.Boolean(), nullable=True),
    sa.Column('ethnic_belonging', sa.Boolean(), nullable=True),
    sa.Column('is_narp', sa.Boolean(), nullable=True),
    sa.Column('is_victim_conflict', sa.Boolean(), nullable=True),
    sa.Column('control_resources', sa.Integer(), nullable=True),
    sa.Column('control_resources_evidence', sa.Text(), nullable=True),
    sa.Column('decision_voice', sa.Integer(), nullable=True),
    sa.Column('decision_voice_evidence', sa.Text(), nullable=True),
    sa.Column('innovation_leadership', sa.Integer(), nullable=True),
    sa.Column('innovation_leadership_evidence', sa.Text(), nullable=True),
    sa.Column('knowledge_dialogue', sa.Integer(), nullable=True),
    sa.Column('knowledge_dialogue_evidence', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('development', sa.Text(), nullable=True),
    sa.Column('final_diagnosis', sa.Text(), nullable=True),
    sa.Column('fulfilled_previous_recommendations', sa.Boolean(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('photo_user', sa.String(length=255), nullable=True),
    sa.Column('photo_interaction', sa.String(length=255), nullable=True),
    sa.Column('photo_development', sa.String(length=255), nullable=True),
    sa.Column('phono_extra_1', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['extensionist_id'], ['user_extensionist.id'], ),
    sa.ForeignKeyConstraint(['producter_id'], ['user_producter.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['product_property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_3')
    op.drop_table('survey_2')
    op.drop_table('survey_1')
    op.drop_table('user_producter')
    op.drop_index(op.f('ix_user_extensionist_api_token'), table_name='user_extensionist')
    op.drop_table('user_extensionist')
    op.drop_table('product_property')
    # ### end Alembic commands ###
