"""add fields to survey 3

Revision ID: b09ab1324207
Revises: 101a0b831ecc
Create Date: 2025-11-09 19:55:47.023284

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b09ab1324207"
down_revision: Union[str, Sequence[str], None] = "101a0b831ecc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "survey_3", sa.Column("visit_date", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "survey_3", sa.Column("attended_by", sa.String(length=255), nullable=True)
    )
    op.add_column("survey_3", sa.Column("user", sa.String(length=255), nullable=True))
    op.add_column(
        "survey_3", sa.Column("worker_up", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "survey_3", sa.Column("household_size", sa.String(length=50), nullable=True)
    )
    op.add_column("survey_3", sa.Column("other", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("survey_3", "other")
    op.drop_column("survey_3", "household_size")
    op.drop_column("survey_3", "worker_up")
    op.drop_column("survey_3", "user")
    op.drop_column("survey_3", "attended_by")
    op.drop_column("survey_3", "visit_date")
    # ### end Alembic commands ###
