from typing import Optional
from common.domain import entities as common_entities
from pydantic import Field


class ClassificationUser(common_entities.BaseEntity):
    survey_idd1: Optional[int] = Field(None)
    survey_idd3: Optional[int] = Field(None)
    main_productive_activity: Optional[int] = Field(None)
    secondary_productive_activities: Optional[int] = Field(None)
    tools_and_equipment: Optional[int] = Field(None)
    good_agricultural_practices: Optional[int] = Field(None)
    commercialization_structure: Optional[int] = Field(None)
    markets: Optional[int] = Field(None)
    added_value: Optional[int] = Field(None)
    records: Optional[int] = Field(None)
    labor_type: Optional[int] = Field(None)
    credit_and_banking: Optional[int] = Field(None)
    organization_membership: Optional[int] = Field(None)
    collective_activities: Optional[int] = Field(None)
    entrepreneurship_associativity: Optional[int] = Field(None)
    commercial_alliances: Optional[int] = Field(None)
    technical_support: Optional[int] = Field(None)
    quality_certifications: Optional[int] = Field(None)
    intellectual_property: Optional[int] = Field(None)
    access_information_sources: Optional[int] = Field(None)
    access_to_ict: Optional[int] = Field(None)
    use_of_ict_decision: Optional[int] = Field(None)
    ict_skills: Optional[int] = Field(None)
    knowledge_appropriation: Optional[int] = Field(None)
    environmental_practices: Optional[int] = Field(None)
    sustainable_practices: Optional[int] = Field(None)
    climate_change_adaptation: Optional[int] = Field(None)
    environmental_regulations: Optional[int] = Field(None)
    participation_mechanisms: Optional[int] = Field(None)
    participation_tools: Optional[int] = Field(None)
    political_social_control: Optional[int] = Field(None)
    community_self_management: Optional[int] = Field(None)
